-- $Id$
unitDef = {
  unitname            = [[bluar]],
  name                = [[Hillenkoetter UAV]],
  description         = [[Air Scout]],
  amphibious          = false,
  --autoheal            = 50,
  buildCostEnergy     = 0,
  buildCostMetal      = 0,
  buildTime           = 0,
 -- canAttack           = true,
  canDropFlare        = false,
  canFireControl 	    = 1,
  canFly              = true,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canstop             = [[1]],
  canSubmerge         = false,
  category            = [[VTOL AIR NOTINF TARGET]], 
  collide             = false,
  cruiseAlt           = 250,

  customParams        = {
	toggle1 = 2,
	toggle1on = [[Radar On]],
	toggle1off = [[Radar Off]],
	toggle1tooltip = [[Visual or Radar Mode]],
	helptext = [[The UAV is the primary Reconnisance Vehicle in the Coalition Force]],
  },

  defaultmissiontype  = [[VTOL_standby]],
  explodeAs           = [[death]],
  floater             = true,
  footprintX          = 1,
  footprintZ          = 1,
  frontToSpeed        = 0,
  iconType            = [[aa]],
  idleAutoHeal        = 1,
  idleTime            = 300,
  maneuverleashlength = [[1280]],
  mass                = 100,
  maxAcc              = 0.6,
  maxDamage           = 800,
  --maxFuel             = 290,
  maxVelocity         = 8,
  MaxWaterDepth 	    = 1,
  noChaseCategory     = [[TARGET NOTARGET]],
  objectName          = [[bluar.s3o]],
  seismicSignature    = 0,
  selfDestructAs      = [[death]],
  side                = [[BLU]],
  sightDistance       = 1200,
  RadarDistance		  = 1200,
  smoothAnim          = true,
  speedToFront        = 0,
  Stealth	          = true,
  TEDClass            = [[VTOL]],
  turnRate            = 700,
  verticalSpeed 	    = 1,


}

return lowerkeys({ bluar = unitDef })
