-- $Id$
unitDef = {
  unitname            = [[blutub]],
  name                = [[Weapon Truck]],
  description         = [[Carriers Weapon Systems to Deploy in the Battlefield]],
  brakeRate			  = 0.2,
  buildCostEnergy     = 200,
  buildCostMetal      = 200,
  buildTime           = 0,
  builddistance = 128,
  builder = true,
  canGuard            = true,
  canMove             = true,
    canRepair = false,
	canRestore = false,
	canReclaim = false,
	canAssist = false,
  canPatrol           = true,
  canstop             = [[1]],
  category            = [[VEH UNIT TARGET NOTINF]], 
 corpse              = [[dead]],
  explodeAs           = [[death]],
  footprintX          = 1,
  footprintZ          = 2,
  frontToSpeed        = 0,
  iconType            = [[tub]],
  idleAutoHeal        = 50,
  idleTime            = 300,
  leavetracks = 1, 
	trackwidth = 7, 
	trackoffset = 0, 
	trackstrength = 8, 
	trackstretch = 1,
	tracktype = "StdTank",
  mass                = 9000,
  maxAcc              = 0.3,
  maxDamage           = 2500, 
  maxVelocity         = 0.5,
  MaxWaterDepth 	  = 1,
  MovementClass		  = "WHEEL",
  noChaseCategory     = [[NOTINF NOTARGET]],
  objectName          = [[dumtruk.s3o]],
  seismicSignature    = 4,
  selfDestructAs      = [[death]],
  side                = [[BLU]],
  sightDistance       = 800,
  transportsize = 1,
	transportcapacity = 6,
	transportmaxunits = 6,
	transportUnloadMethod = 2,
	transportmass = 900,
	releaseHeld = true,
  turnInPlace		  = false,
  turnRate            = 600,
  workertime = 100,
	buildoptions = {
			[1] = "port",
		},
	sounds = {
			canceldestruct = "RadAcknow",
			underattack = {
				[1] = "RadNeedBack",
				[2] = "RadTaking",
			},
			cant = {
				[1] = "RadCant",
			},
			ok = {
				[1] = "veh1",
				[2] = "RadAcknow",
				[3] = "veh4",
				[4] = "RadRoger",
			},
			select = {
				[1] = "veh2",
				[2] = "veh3",
				[3] = "veh4",
			},
			arrived = {
				[1] = "vehstop",
				[2] = "vehstop2",
			},
		},
		
featureDefs         = {
		DEAD  = {
		  description      = [[Wreckage - blutub]],
		  blocking         = true,
		  category         = [[corpses]],
		  damage           = 5000,
		  energy           = 0,
		  featurereclamate = [[SMUDGE01]],
		  footprintX       = 1,
		  footprintZ       = 2,
		  height           = [[12]],
		  hitdensity       = [[1]],
		  metal            = 0,
		  object           = [[blui_dead.s3o]],
		  reclaimable      = false,
		  reclaimTime      = 0,
		  world            = [[All Worlds]],
				},
	},

}

return lowerkeys({ blutub = unitDef })
