-- $Id$
unitDef = {
  unitname            = [[bluaa]],
  name                = [[Gyrfalcon]],
  description         = [[Interceptor Aircraft]],
  amphibious          = false,
  autoheal            = 5,
  buildCostEnergy     = 0,
  buildCostMetal      = 0,
  buildTime           = 0,
  canAttack           = true,
  canDropFlare        = false,
  canFireControl 	    = 1,
  canFly              = true,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canstop             = [[1]],
  canSubmerge         = false,
  category            = [[VTOL AIR NOTINF TARGET]], 
  collide             = false,
  corpse              = [[DEAD]],
  cruiseAlt           = 300,

  customParams        = {
	toggle1 = 2,
	toggle1on = [[Strike On]],
	toggle1off = [[Strike Off]],
	toggle1tooltip = [[Air to Surface Strike or Anti Air Missile]],
	helptext = [[The Gyrfalcon Interceptor Aircraft's primary role is anti air interdiction, but has the ability to use its missiles on surface targets]],
  },

  defaultmissiontype  = [[VTOL_standby]],
  explodeAs           = [[death]],
  floater             = true,
  footprintX          = 1,
  footprintZ          = 1,
  frontToSpeed        = 0,
  iconType            = [[aa]],
  idleAutoHeal        = 50,
  idleTime            = 300,
  maneuverleashlength = [[1280]],
  mass                = 4500,
  maxAcc              = 1.5,
  maxDamage           = 1250,
  maxFuel             = 290,
  maxVelocity         = 15,
  MaxWaterDepth 	    = 1,
  noChaseCategory     = [[NOTAIR NOTARGET]],
  objectName          = [[bluaa.s3o]],
  seismicSignature    = 0,
  selfDestructAs      = [[death]],
sfxtypes           = {

    explosiongenerators = {
      [[custom:AfterBurner]],
     	[[custom:FF_WINGTIPS]],
    },
},
  side                = [[BLU]],
  sightDistance       = 1200,
  smoothAnim          = true,
  speedToFront        = 0,
  TEDClass            = [[VTOL]],
  turnRate            = 720,
  verticalSpeed 	    = 1,

  weapons             = {

    {
      def                = [[BLUAAWPN1]],
      badTargetCategory  = [[NOTAIR NOTARGET]],
	fuelUsage          = 25,
      mainDir            = [[0 0 1]],
      maxAngleDif        = 120,
      onlyTargetCategory = [[AIR VTOL]],
    },

{
      def                = [[BLUAAWPN2]],
      badTargetCategory  = [[AIR NOTARGET]],
	fuelUsage          = 25,
      mainDir            = [[0 0 1]],
      maxAngleDif        = 120,
      onlyTargetCategory = [[NOTAIR TARGET]],
    },

  },


  weaponDefs          = {

    BLUAAWPN1 = {
      name                    = [[Anti Air Missile]],
      areaOfEffect            = 20,
      craterBoost             = 1,
      craterMult              = 1,

      damage                  = {
        default = 1600,
        air  = [[2400]],
        def  = 0,
      },

      explosionGenerator      = [[custom:MISSILE_EXPLOSION]], -- was FLASH2 
      fireStarter             = 70,
      flightTime              = 3,
      guidance                = true,
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      InterceptedByShieldType = 2,
	lineOfSight             = true,
      metalpershot            = 0,
      model                   = [[genaamis.s3o]],
      noSelfDamage            = true,
      range                   = 960,
      reloadtime              = 8,
      renderType              = 1,
      selfprop                = true,
      smokedelay              = [[0.1]],
      smokeTrail              = true,
      soundHit                = [[missile2]],
      soundStart              = [[medexplo]],
      startsmoke              = [[1]],
      startVelocity           = 500,
      tolerance               = 10000,
      tracks                  = true,
      turnRate                = 12000,
      turret                  = true,
      weaponAcceleration      = 150,
      weaponTimer             = 5,
      weaponType              = [[MissileLauncher]],
      weaponVelocity          = 850,

    },

BLUAAWPN2 = {
      name                    = [[Air to Surface Missile]],
      areaOfEffect            = 30,
      craterBoost             = 1,
      craterMult              = 1,

      damage                  = {
        default = 1600,
        air  = [[800]],
        def  = 800,
	  inf = 150,
	  base = 0,
      },

      explosionGenerator      = [[custom:MISSILE_EXPLOSION]], 
      fireStarter             = 70,
      flightTime              = 3,
      guidance                = true,
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      InterceptedByShieldType = 2,
      lineOfSight             = true,
      metalpershot            = 0,
      model                   = [[genaamis.s3o]],
      noSelfDamage            = true,
      range                   = 600,
      reloadtime              = 8,
      renderType              = 1,
      selfprop                = true,
      smokedelay              = [[0.1]],
      smokeTrail              = true,
      soundHit                = [[missile2]],
      soundStart              = [[medexplo]],
      startsmoke              = [[1]],
      startVelocity           = 300,
      tolerance               = 10000,
      tracks                  = true,
      turnRate                = 6000,
      turret                  = true,
      weaponAcceleration      = 100,
      weaponTimer             = 5,
      weaponType              = [[MissileLauncher]],
      weaponVelocity          = 650,

    },

  },


  featureDefs         = {
    DEAD  = {
      description      = [[Wreckage - bluaa]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 3000,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 1,
      footprintZ       = 1,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 0,
      object           = [[bluaa_dead.s3o]],
      reclaimable      = false,
      reclaimTime      = 0,
      world            = [[All Worlds]],
    },  
},

}

return lowerkeys({ bluaa = unitDef })
