-- $Id$
unitDef = {
  unitname            = [[bluav]],
  name                = [[Python]],
  description         = [[Attack Gunship]],
  acceleration        = 0.5,
  amphibious          = true,
  bankscale           = [[1]],
  bmcode              = [[1]],
  brakeRate           = 0.5,
  buildCostEnergy     = 0,
  buildCostMetal      = 0,
  builder             = false,
  buildTime           = 0,
  canAttack           = true,
  canFly              = true,
  canFireControl      = 1,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canstop             = [[1]],
  canSubmerge         = false,
  category            = [[VTOL AIR NOTINF TARGET]],
  collide             = true,
  corpse              = [[DEAD]],
  cruiseAlt           = 200,

  customParams        = {
   	toggle1 = 2,
	toggle1on = [[Volley On]],
	toggle1off = [[Volley Off]],
	toggle1tooltip = [[Rocket Volley or Anti Vehicle Gun]],
    helptext       = [[The Brawler is Nova's Heavy Assault Gunship. It has enough armor to survive limited anti-air fire, and its twin EMGs chew through the Logos' advanced alloys as if they were paper.]],
     },

  defaultmissiontype  = [[VTOL_standby]],
  drag		    = 0.05,
  explodeAs           = [[death]],
  floater             = true,
  footprintX          = 1,
  footprintZ          = 1,
  hoverAttack         = true,
  iconType            = [[av]],
  idleAutoHeal        = 5,
  idleTime            = 300,
  maneuverleashlength = [[1280]],
  mass                = 4000,
  maxDamage           = 3000,
  maxFuel             = 250,
  maxVelocity         = 8,
  MaxWaterDepth 	    = 1,
  noAutoFire          = false,
  noChaseCategory     = [[AIR NOTARGET]],
  objectName          = [[bluav.s3o]],
  scale               = [[1.5]],
  seismicSignature    = 0,
  selfDestructAs      = [[DEATH]],

  sfxtypes            = {

    explosiongenerators = {
      [[custom:flashmuzzle1]],
      [[custom:flashmuzzle0]],
    },

  },

  side                = [[BLU]],
  sightDistance       = 1200,
  smoothAnim          = true,
  steeringmode        = [[1]],
  TEDClass            = [[VTOL]],
  turnRate            = 792,
  workerTime          = 0,

  weapons             = {

    {
      def                = [[bluavwpn1]],
	badTargetCategory  = [[NOTARGET AIR]],
      mainDir            = [[0 -0.35 1]],
      maxAngleDif        = 120,
      onlyTargetCategory = [[NOTAIR TARGET]],
    },

 {
      def                = [[bluavwpn2]],
	badTargetCategory  = [[NOTARGET AIR]],
	fuelUsage          = 100,
      mainDir            = [[0 0 1]],
      maxAngleDif        = 90,
      onlyTargetCategory = [[NOTAIR TARGET]],
    },

  },


  weaponDefs          = {

    BLUAVWPN1 = {
      name                    = [[Auto Cannon]],
      areaOfEffect            = 20,
      avoidFeature            = false,
      burst                   = 4,
      burstrate               = 0.1,
      collideFriendly         = false,
      craterBoost             = 0.15,
      craterMult              = 0.15,

      damage                  = {
        default = 300,
        base    = 0,
        veh = 450,
        def = 200,
	  inf = 150,
      },

      edgeEffectiveness       = 0.5,
      endsmoke                = [[0]],
      explosionGenerator      = [[custom:flashplosion]],
      firestarter             = 70,
	impactOnly 			= 1,
      impulseBoost            = 0,
      impulseFactor           = 0.2,
      InterceptedByShieldType = 2,
      lineOfSight             = true,
      noSelfDamage            = true,
      pitchtolerance          = 12000,
      range                   = 500,
      reloadtime              = 4,
      renderType              = 4,
      rgbColor                = [[1 0.95 0.5]],
      soundHit                = [[Rifle]],
      soundStart              = [[medcan]],
      sprayAngle              = 300,
      startsmoke              = [[0]],
      sweepfire               = false,
      tolerance               = 2000,
      turret                  = true,
      weaponTimer             = 1,
      weaponType              = [[Cannon]],
      weaponVelocity          = 1150,
    },

BLUAVWPN2 = {
      name                    = [[Air to Surface Rocket]],
      areaOfEffect            = 40,
 	burst                   = 8,
      burstrate               = 0.5,
	craterBoost             = 1,
      craterMult              = 1,

      damage                  = {
        default = 450,
	  veh = 650,
        air  = 100,
        def  = 350,
	  base = 0,
	  inf = 150,	
      },

      explosionGenerator      = [[custom:MISSILE_EXPLOSION]], -- was FLASH2 
      fireStarter             = 70,
      flightTime              = 3,
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      InterceptedByShieldType = 2,
      lineOfSight             = true,
      metalpershot            = 0,
      model                   = [[genaamis.s3o]],
      noSelfDamage            = true,
      range                   = 500,
      reloadtime              = 8,
      renderType              = 1,
      selfprop                = true,
      smokedelay              = [[0.1]],
      smokeTrail              = true,
      soundHit                = [[Rocket]],
      soundStart              = [[smallexplo]],
      startsmoke              = [[1]],
      startVelocity           = 400,
      tolerance               = 10000,
      turret                  = true,
      weaponAcceleration      = 100,
      weaponTimer             = 5,
      weaponType              = [[MissileLauncher]],
      weaponVelocity          = 500,
    },
 },

featureDefs         = {
    DEAD  = {
      description      = [[Wreckage - bluav]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 3000,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 1,
      footprintZ       = 1,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 0,
      object           = [[bluav_dead.s3o]],
      reclaimable      = false,
      reclaimTime      = 0,
      world            = [[All Worlds]],
    },
  },

 }

return lowerkeys({ bluav = unitDef })
