unitDef = {
  unitname            = "gentub",
  name                = "LCAC",
  description         = "Heavy Transport",
  acceleration        = 0.043,
  bmcode              = "1",
  brakeRate           = 0.062,
  buildAngle          = 16384,
  buildCostEnergy     = 0,
  buildCostMetal      = 0,
  builder             = false,
  --buildPic            = "",
  buildTime           = 724.953,
  canAttack           = true,
  canGuard            = true,
  canHover            = true,
  canload             = "1",
  canMove             = true,
  canPatrol           = true,
  canstop             = "1",
  cantBeTransported   = true,
  category            = "VEH UNIT TARGET NOTAIR NOTINF",
  corpse              = "DEAD",
  defaultmissiontype  = "Standby",
  explodeAs           = "death",
  footprintX          = 2,
  footprintZ          = 2,
  iconType            = "failboat",
  idleAutoHeal        = 2,
  idleTime            = 1800,
  maneuverleashlength = "640",
  mass                = 140000,
  maxDamage           = 6000,
  maxSlope            = 18,
  maxVelocity         = 2.4,
  minWaterDepth       = 12,
  movementClass       = "HOVER",
  noAutoFire          = false,
  noChaseCategory     = "VTOL",
  objectName          = "gentub.s3o",
  scale               = "1.1",
  seismicSignature    = 2,
  selfDestructAs      = "death",
  side                = "gen",
  sightDistance       = 800, --veh are 800
  smoothAnim          = true,
  steeringmode        = "1",
  TEDClass            = "TANK",
  transportCapacity   = 1,
  TransportMass	    = 100000,
  transportSize       = 4,
  turnInPlace	    = 1,
  turnRate            = 395,
  waterline           = 0,
  workerTime          = 0,

  featureDefs         = {

    DEAD = {
      description      = "Wreckage - Toot Toot",
      blocking         = false,
      category         = "corpses",
      damage           = 5800,
      energy           = 0,
     -- featureDead      = "HEAP",
      footprintX       = 2,
      footprintZ       = 3,
      height           = "15",
      hitdensity       = "100",
      metal            = 0,
      object           = "gentub_dead.s3o",
      reclaimable      = false,
      reclaimTime      = 999,
      seqnamereclamate = "TREE1RECLAMATE",
      world            = "All Worlds",
    },


   -- HEAP = {
   -- },

  },

}

return lowerkeys({ gentub = unitDef })
